"""
build.py  —  Static site builder for the Data Science Portfolio Template.

Usage:
    uv run python build.py

What this script does:
  1. Reads portfolio_config.yaml.
  2. Loads profile, project, and writing YAML.
  3. Renders templates/index.html into docs/index.html.
  4. Copies static assets and writes docs/css/site.css.

After running this script, open docs/index.html in a browser or run
  uv run python serve.py
to preview the site locally.
"""

import shutil
import sys
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse

import markdown
import yaml
from jinja2 import Environment, FileSystemLoader, select_autoescape


# ── Paths ──────────────────────────────────────────────────────────────────
ROOT = Path(__file__).parent          # repo root
TEMPLATES_DIR = ROOT / "templates"
STATIC_DIR    = ROOT / "static"
DOCS_DIR      = ROOT / "docs"
CONFIG_FILE   = ROOT / "portfolio_config.yaml"


# ── Helpers ────────────────────────────────────────────────────────────────

def load_yaml(path: Path) -> dict:
    """Read a YAML file and return its contents as a Python dictionary."""
    with open(path, encoding="utf-8") as f:
        return yaml.safe_load(f)


def youtube_embed_url(url: str, start_seconds: int = 0, captions: bool = False, captions_lang: str = "en") -> str:
    """Return a YouTube embed URL for common watch/share URL formats."""
    parsed = urlparse(url)
    host = parsed.netloc.lower().removeprefix("www.")

    if host in {"youtube.com", "m.youtube.com"}:
        video_id = parse_qs(parsed.query).get("v", [""])[0]
    elif host == "youtu.be":
        video_id = parsed.path.strip("/").split("/")[0]
    else:
        return url

    video_id = video_id.split("?")[0]
    if not video_id:
        return url

    params = {}
    if start_seconds:
        params["start"] = max(0, int(start_seconds))
    if captions:
        params["cc_load_policy"] = 1
        params["cc_lang_pref"] = captions_lang

    query = f"?{urlencode(params)}" if params else ""
    return f"https://www.youtube-nocookie.com/embed/{video_id}{query}"


def clean_docs_dir() -> None:
    """Remove generated output before rebuilding."""
    if DOCS_DIR.exists():
        shutil.rmtree(DOCS_DIR)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)


def should_copy_static_file(path: Path) -> bool:
    """Skip local metadata files that should not be published."""
    return not any(part.startswith(".") for part in path.parts)


def copy_static_asset(asset_path: str) -> None:
    """Copy one referenced static asset into docs/."""
    if not asset_path:
        return

    relative = Path(asset_path)
    if not should_copy_static_file(relative):
        return

    src = STATIC_DIR / relative
    dest = DOCS_DIR / relative
    if not src.exists():
        return

    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dest)
    print(f"  copied  static/{relative}")


def copy_referenced_assets(student: dict, projects: list[dict]) -> None:
    """Copy only assets referenced by YAML content."""
    copy_static_asset(student.get("headshot"))

    for project in projects:
        copy_static_asset(project.get("image_path"))


def write_combined_styles(theme: str) -> None:
    """Combine base.css and the selected theme into one deploy stylesheet."""
    base_css = STATIC_DIR / "css" / "base.css"
    theme_css = STATIC_DIR / "css" / "themes" / f"{theme}.css"
    output_css = DOCS_DIR / "css" / "site.css"

    if not base_css.exists():
        sys.exit(f"Error: base stylesheet not found: {base_css}")
    if not theme_css.exists():
        sys.exit(f"Error: theme stylesheet not found: {theme_css}")

    output_css.parent.mkdir(parents=True, exist_ok=True)
    output_css.write_text(
        "/* Generated by build.py. Do not edit docs/css/site.css directly. */\n\n"
        f"/* base.css */\n{base_css.read_text(encoding='utf-8')}\n\n"
        f"/* themes/{theme}.css */\n{theme_css.read_text(encoding='utf-8')}\n",
        encoding="utf-8",
    )
    print(f"  wrote   css/site.css  (base + {theme})")


def warn_if_missing_static_asset(asset_path: str, context: str) -> None:
    if not asset_path:
        return

    p = STATIC_DIR / asset_path
    if not p.exists():
        print(f"  [warn] Missing asset for {context}: static/{asset_path}")


def validate_student(student: dict) -> None:
    warn_if_missing_static_asset(student.get("headshot"), "student headshot")

    endpoint = student.get("formspree_endpoint", "")
    if endpoint and "YOUR_FORM_ID" in endpoint:
        print("  [warn] Formspree endpoint still uses YOUR_FORM_ID placeholder.")

    video_url = student.get("featured_video_url")
    embed_url = student.get("featured_video_embed_url")
    if video_url and embed_url == video_url:
        print(f"  [warn] Featured video URL was not converted to an embed URL: {video_url}")


def validate_projects(projects: list[dict]) -> None:
    for project in projects:
        title = project.get("title", "Untitled project")
        warn_if_missing_static_asset(project.get("image_path"), title)


# ── Main build ─────────────────────────────────────────────────────────────

def build() -> None:
    print("=" * 55)
    print("  Building portfolio site → docs/")
    print("=" * 55)

    # ── 1. Load config ──────────────────────────────────────────────────
    if not CONFIG_FILE.exists():
        sys.exit(f"Error: {CONFIG_FILE} not found. Are you running from the repo root?")

    config = load_yaml(CONFIG_FILE)
    print(f"\n[1/5] Loaded config:  {CONFIG_FILE.name}")

    theme       = config.get("theme", "light")
    site_title  = config.get("site_title", "My Portfolio")
    asset_version = config.get("asset_version", "1")
    student_rel = config.get("student_file", "content/example_student.yaml")
    project_rel = config.get("projects", [])
    writing_rel = config.get("writing_posts", config.get("blog_posts", []))

    theme_path = STATIC_DIR / "css" / "themes" / f"{theme}.css"
    if not theme_path.exists():
        sys.exit(f"Error: theme '{theme}' not found at static/css/themes/{theme}.css")

    # ── 2. Load student profile ─────────────────────────────────────────
    student_path = ROOT / student_rel
    if not student_path.exists():
        sys.exit(f"Error: student file '{student_rel}' not found.")

    student = load_yaml(student_path)
    # Convert the about field from Markdown to HTML so students can use
    # standard Markdown syntax: blank lines for paragraphs, *italic*, **bold**, etc.
    if student.get("about"):
        student["about"] = markdown.markdown(student["about"])
    if student.get("featured_video_url"):
        student["featured_video_embed_url"] = youtube_embed_url(
            student["featured_video_url"],
            student.get("featured_video_start_seconds", 0),
            student.get("featured_video_captions", False),
            student.get("featured_video_captions_lang", "en"),
        )
    validate_student(student)
    print(f"[2/5] Loaded student: {student_path.name}  ({student.get('name', '?')})")

    # ── 3. Load project files ───────────────────────────────────────────
    projects = []
    for rel in project_rel:
        p = ROOT / rel
        if not p.exists():
            print(f"  [warn] Project file not found, skipping: {rel}")
            continue
        projects.append(load_yaml(p))
        print(f"       project: {p.name}")

    validate_projects(projects)
    print(f"[3/5] Loaded {len(projects)} project(s).")


     # ── 4. Load writing files ───────────────────────────────────────────
    writing_posts = []
    for rel in writing_rel:
        p = ROOT / rel
        if not p.exists():
            print(f"  [warn] Writing file not found, skipping: {rel}")
            continue

        post = load_yaml(p)

        # convert markdown to HTML for content
        if post.get("content"):
            post["content"] = markdown.markdown(post["content"])

        writing_posts.append(post)
        print(f"       writing: {p.name}")

    # ── 5. Render HTML ──────────────────────────────────────────────────
    clean_docs_dir()

    env = Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=select_autoescape(["html"]),
    )

    template = env.get_template("index.html")
    rendered = template.render(
        site_title=site_title,
        theme=theme,
        asset_version=asset_version,
        student=student,
        projects=projects,
        writing_posts=writing_posts,
    )

    output_path = DOCS_DIR / "index.html"
    output_path.write_text(rendered, encoding="utf-8")
    print(f"[5/5] Rendered → {output_path.relative_to(ROOT)}")

    # ── 6. Copy static assets ───────────────────────────────────────────
    print("\n      Writing static assets …")
    copy_referenced_assets(student, projects)
    write_combined_styles(theme)

    print("\n✓  Build complete.  Open docs/index.html or run: uv run python serve.py")
    print("=" * 55)


if __name__ == "__main__":
    build()
